import type { DriveItem, FileItem, FolderItem, StorageQuota } from '../types/file.types';

// Mock user data
export const MOCK_USER_ID = 'user-001';

// Mock files and folders
export const mockFiles: DriveItem[] = [
  // Folders
  {
    id: 'folder-1',
    name: 'Documents',
    type: 'folder',
    childrenCount: 5,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-01-15'),
    modifiedTime: new Date('2024-10-20'),
    parentId: null,
    path: [],
    isStarred: true,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FolderItem,
  {
    id: 'folder-2',
    name: 'Projects',
    type: 'folder',
    childrenCount: 12,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-02-10'),
    modifiedTime: new Date('2024-10-25'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: true,
    permissions: [],
  } as FolderItem,
  {
    id: 'folder-3',
    name: 'Photos',
    type: 'folder',
    childrenCount: 48,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-03-05'),
    modifiedTime: new Date('2024-10-28'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FolderItem,

  // Files
  {
    id: 'file-1',
    name: 'Project Proposal.pdf',
    type: 'pdf',
    mimeType: 'application/pdf',
    size: 2456789,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-10-15'),
    modifiedTime: new Date('2024-10-15'),
    lastOpenedTime: new Date('2024-10-30'),
    parentId: null,
    path: [],
    isStarred: true,
    isTrashed: false,
    isShared: true,
    permissions: [],
  } as FileItem,
  {
    id: 'file-2',
    name: 'Budget_2024.xlsx',
    type: 'spreadsheet',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 145678,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-10-20'),
    modifiedTime: new Date('2024-10-29'),
    lastOpenedTime: new Date('2024-10-31'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FileItem,
  {
    id: 'file-3',
    name: 'Meeting Notes.docx',
    type: 'document',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 45678,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-10-25'),
    modifiedTime: new Date('2024-10-30'),
    lastOpenedTime: new Date('2024-10-31'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: true,
    permissions: [],
  } as FileItem,
  {
    id: 'file-4',
    name: 'Vacation_Photo.jpg',
    type: 'image',
    mimeType: 'image/jpeg',
    size: 3456789,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-09-10'),
    modifiedTime: new Date('2024-09-10'),
    parentId: null,
    path: [],
    isStarred: true,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FileItem,
  {
    id: 'file-5',
    name: 'Presentation.pptx',
    type: 'presentation',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 8456789,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-10-01'),
    modifiedTime: new Date('2024-10-28'),
    lastOpenedTime: new Date('2024-10-29'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: true,
    permissions: [],
  } as FileItem,
  {
    id: 'file-6',
    name: 'Tutorial_Video.mp4',
    type: 'video',
    mimeType: 'video/mp4',
    size: 45678901,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-08-15'),
    modifiedTime: new Date('2024-08-15'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FileItem,
  {
    id: 'file-7',
    name: 'Archive.zip',
    type: 'archive',
    mimeType: 'application/zip',
    size: 12345678,
    ownerId: MOCK_USER_ID,
    ownerName: 'John Doe',
    ownerEmail: 'john.doe@example.com',
    createdTime: new Date('2024-07-20'),
    modifiedTime: new Date('2024-07-20'),
    parentId: null,
    path: [],
    isStarred: false,
    isTrashed: false,
    isShared: false,
    permissions: [],
  } as FileItem,
];

// Mock storage quota
export const mockStorageQuota: StorageQuota = {
  limit: 15 * 1024 * 1024 * 1024, // 15 GB
  usage: 8.5 * 1024 * 1024 * 1024, // 8.5 GB used
  usageInDrive: 7 * 1024 * 1024 * 1024, // 7 GB
  usageInTrash: 1.5 * 1024 * 1024 * 1024, // 1.5 GB
};
